/** Publishing a project to a public origin.
 *
 *  The preview proxy shows a *dev* server to somebody who already has a
 *  session, behind a container that is stopped once it goes idle. A deployment
 *  drops all three: a build rather than a dev server, no session required, and
 *  a lifetime that does not end when the author closes the tab. That is what
 *  makes a link shareable with somebody who has never heard of this platform.
 *
 *  There are two shapes of it, because projects come in two shapes:
 *
 *  - **static** — the build emits a directory of files, which are copied out
 *    and served with no container behind them at all. Cheap, and the right
 *    answer whenever it is available.
 *  - **service** — the project answers requests from a running process, so
 *    there is nothing to copy. A container of its own stays up and the public
 *    origin reverse-proxies to it. This costs memory for as long as it is
 *    published, which is why it is not the default for anything that could be
 *    static.
 */

export type DeploymentStatus = "building" | "live" | "failed";

/** Which of the two mechanisms above a deployment uses.
 *
 *  Recorded on the deployment rather than derived from the template at read
 *  time, for the same reason `buildCommand` is: a template gaining a static
 *  build later must not silently change what an already-published site claims
 *  to be, nor how it is served.
 */
export type DeploymentKind = "static" | "service";

/** What a project's deployment looks like to the editor. */
export interface Deployment {
  status: DeploymentStatus;
  /** Static files, or a running container. */
  kind: DeploymentKind;
  /** The generated subdomain label, e.g. "quiet-fern-84f1". */
  subdomain: string;
  /** Absolute, public, and unauthenticated. Null while the first build of a
   *  never-yet-published project is still running. */
  url: string | null;
  /** The command that produced it, and the directory it read afterwards.
   *  Recorded per deployment rather than looked up, so a template's defaults
   *  changing does not rewrite the history of what actually ran.
   *
   *  For a service deployment `outputDir` is empty: nothing is read back,
   *  because the command does not terminate. */
  buildCommand: string;
  outputDir: string;
  /** The container port a service deployment is proxied to, or null for a
   *  static one. */
  port: number | null;
  /** Total bytes published. For a service, the size of the copied source
   *  tree rather than of a build output. */
  sizeBytes: number;
  /** Tail of the build's own output, so a failure can be read where it
   *  happened rather than only in the terminal. */
  log: string;
  /** Why the last attempt failed, or null. */
  error: string | null;
  /** ISO timestamp of the last build that went live, or null if none has. */
  deployedAt: string | null;
  /** A hostname the owner has pointed here, or null. Present on the row long
   *  before it is verified, because the claim is what the setup instructions
   *  are rendered from. */
  customDomain: CustomDomain | null;
}

/** How a project CAN be deployed, worked out from its template.
 *
 *  Sent to the editor so the panel can explain the answer up front instead of
 *  offering a button that always fails.
 */
export interface DeployTarget {
  deployable: boolean;
  /** Which mechanism would be used. Meaningless when `deployable` is false.
   *
   *  Static wins wherever a template offers both, and no template offers
   *  both today: a directory of files needs no container, cannot crash, and
   *  costs nothing to keep published. Service exists for the projects that
   *  have no such directory to offer. */
  kind: DeploymentKind;
  /** Present when `deployable` is false: the reason, in the user's terms. */
  reason?: string;
  /** The command that would run: a build for a static target, the long-lived
   *  serve command for a service one, or "" for a template with no build step
   *  at all (static HTML is already its own output). */
  buildCommand: string;
  /** Directory, relative to the project root, published afterwards. Empty for
   *  a service target, which publishes no directory. */
  outputDir: string;
  /** The container port a service target would be proxied to, or null for a
   *  static one. */
  port: number | null;
}

/** Everything the deployment panel needs in one request. */
export interface DeploymentState {
  target: DeployTarget;
  deployment: Deployment | null;
}

/** A DNS label: at most 63 characters, and the only characters a hostname may
 *  carry. Enforced on the way in AND on the way out, because this value becomes
 *  both a hostname and a directory name. */
export const SUBDOMAIN_PATTERN = /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/;

export const MAX_SUBDOMAIN = 63;

/* ---- custom domains ---- */

/** A hostname the owner controls, pointed at this platform.
 *
 *  Separate from `subdomain` in every way that matters. A subdomain is
 *  generated by the server and is therefore trusted by construction; a custom
 *  domain is claimed by a user about a name the server has no reason to
 *  believe they own. Everything in this shape exists to make that claim
 *  checkable rather than assumed.
 */
export interface CustomDomain {
  /** Lowercased, with any trailing dot removed. */
  domain: string;
  /** Whether the TXT record has been seen. **Only a verified domain is ever
   *  served** — an unverified one is a claim, not an address. */
  verified: boolean;
  /** ISO timestamp of the check that verified it, or null. */
  verifiedAt: string | null;
  /** ISO timestamp of the most recent check of any outcome, or null. A
   *  verified domain is re-checked, because a name can be sold. */
  checkedAt: string | null;
  /** The record to create: `TXT` at this name, with this value. Both are
   *  shown to the owner, because a verification that cannot be explained is
   *  one people work around by guessing. */
  txtName: string;
  txtValue: string;
}

/** The label the verification TXT record hangs off.
 *
 *  A dedicated `_`-prefixed subdomain rather than the apex, because the apex
 *  TXT record of a real domain already carries SPF, DMARC and half a dozen
 *  vendor tokens, and asking somebody to add one more thing to a crowded
 *  record is asking them to break their mail.
 */
export const DOMAIN_TXT_LABEL = "_replit-clone-verify";

/** The longest a hostname may be, in total. */
export const MAX_DOMAIN = 253;

/** A hostname with at least two labels.
 *
 *  Two, not one: a single label is not a domain anybody can own on the public
 *  internet, and accepting one would let a claim be filed against `localhost`
 *  or against an intranet name that resolves differently for the server than
 *  for anyone else. Underscores are excluded even though DNS permits them,
 *  because this value ends up in a certificate request and in an `Origin`.
 */
export const DOMAIN_PATTERN =
  /^(?:[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?\.)+[a-z]{2,63}$/;

/** One published build, kept so it can be gone back to.
 *
 *  A publish used to overwrite its own predecessor, so "put back the one that
 *  worked" had nothing to put back. The live release is a POINTER: every build
 *  keeps its own directory and the deployment names the one being served, so a
 *  rollback is a database write. What comes back is exactly the bytes that
 *  were serving before, not a fresh build of a source tree that has moved on.
 */
export interface DeploymentRelease {
  id: string;
  kind: "static" | "service";
  /** What produced it. Rolling back means rolling back to what that build
   *  actually ran, so it is recorded rather than looked up. */
  buildCommand: string;
  outputDir: string;
  sizeBytes: number;
  log: string;
  createdAt: string;
  /** True for the one currently being served. */
  live: boolean;
}

/** How many builds are kept per site.
 *
 *  Each is a full copy of its output, so this is a disk budget as much as a
 *  history depth. The live release is never pruned however old it is — a
 *  rollback to a fortnight-old build must not make that build the next thing
 *  deleted for being old.
 */
export const RELEASES_KEPT = 5;
